### ISSUE TITLE
Cannot start training

### ISSUE THREAD

**Issue by DavidPL1** [pedrodiamel/ferattention#1]
Hi, I checked out your master branch, installed your pytorchvision package and tried running the bu3dfe training script, but it failed with the following error: 

```
Traceback (most recent call last):
  File "../train.py", line 221, in <module>
    main()
  File "../train.py", line 143, in main
    network.resume( os.path.join(network.pathmodels, args.resume ) )
  File "/home/spectre/anaconda3/envs/thesis/lib/python3.6/site-packages/pytvision-0.0.0-py3.6.egg/pytvision/neuralnet.py", line 287, in resume
  File "/home/spectre/anaconda3/envs/thesis/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'FERAttentionGMMNet' object has no attribute 'module'
```

I am using python 3.6 and pytorch 1.0.1

**Comment by pedrodiamel** [comment]
Hello David,
We created train_bu3dfe.sh for running in multiples GPUs for default ( parallel option ). For single GPU you will have comment the[ line 63](https://github.com/pedrodiamel/ferattention/blob/02e97df4a12129ed6706bddf0d2109650eae8765/runs/train_bu3dfe.sh#L63).  I think that is the problem, I will see, and I will go a return :).

**Comment by DavidPL1** [comment]
Oh, thank you for the hint, I tried running it on a single GPU machine.
