### ISSUE TITLE
Unable to open object (object 'data' doesn't exist)

### ISSUE THREAD

**Issue by HelenGuohx** [pedrodiamel/ferattention#7]
Hi I got this error. And I wonder how you preprocess your images

No protocol specified
=> no checkpoint found at '../out/attnet/feratt_attnet_ferattention_attloss_adam_ck_dim32_bbpreactresnet_fold0_000/models/model_best.pth.tar'
Traceback (most recent call last):
  File "/home/haixuanguo/Documents/ferattention/train.py", line 296, in <module>
    main(params=args)
  File "/home/haixuanguo/Documents/ferattention/train.py", line 154, in main
    data = FactoryDataset.factory(
  File "/home/haixuanguo/Documents/ferattention/torchlib/datasets/factory.py", line 176, in factory
    data = fer.FERClassicDataset(pathname, 'ck', idenselect=idenselect, train=btrain )
  File "/home/haixuanguo/Documents/ferattention/torchlib/datasets/fer.py", line 126, in __init__
    self.data   = np.array(f["data"])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'data' doesn't exist)"

**Comment by daaiwusheng** [comment]
> Hi I got this error. And I wonder how you preprocess your images
> 
> No protocol specified
> => no checkpoint found at '../out/attnet/feratt_attnet_ferattention_attloss_adam_ck_dim32_bbpreactresnet_fold0_000/models/model_best.pth.tar'
> Traceback (most recent call last):
> File "/home/haixuanguo/Documents/ferattention/train.py", line 296, in
> main(params=args)
> File "/home/haixuanguo/Documents/ferattention/train.py", line 154, in main
> data = FactoryDataset.factory(
> File "/home/haixuanguo/Documents/ferattention/torchlib/datasets/factory.py", line 176, in factory
> data = fer.FERClassicDataset(pathname, 'ck', idenselect=idenselect, train=btrain )
> File "/home/haixuanguo/Documents/ferattention/torchlib/datasets/fer.py", line 126, in **init**
> self.data = np.array(f["data"])
> File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 264, in **getitem**
> oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
> File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "h5py/h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object 'data' doesn't exist)"

I got this bug too. Did you solve it?
